"""empty message

Revision ID: 61313c8fb25c
Revises: 7067daf650cf
Create Date: 2022-06-04 21:08:18.444161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61313c8fb25c'
down_revision = '7067daf650cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'genres',
               existing_type=sa.VARCHAR())
    # ### end Alembic commands ###
